language: ruby
rvm:
  - 2.5.1
before_script:
  - chmod +x ./scripts/jcheck
script: ./scripts/jcheck
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
