# site settings
title: Texas Resolution Group
subtitle: L.L.C.
email: intake@txrgp.com
description: 'An innovative virtual debt resolution process… so people can move on with their lives. Texas Resolution Group presents an efficient, less costly, non-adversarial and very
popular procedure to resolve debt issues, both in collections or in the court system. We present a proven alternative to the expensive, time consuming and sometimes intimidating collection and legal processes.'
baseurl:
base_path:
url: "http://txrgp.com" # the base hostname & protocol for your site
author: John Collins
street_address: 14781 Memorial Drive, No 453
city: Houston
state: TX
zip_code: 77079
# country: United States of America
phone: (866) 627-8969

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
# facebook_url:
# github_url:
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
