#!/usr/bin/env bash
set -e

if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
  bundle exec jekyll build
  bundle exec htmlproofer --empty-alt-ignore true ./_site
  aws s3 sync ./_site/ s3://$S3_BUCKET/ --delete --acl public-read
fi
